#!/bin/bash

cd $(dirname $BASH_SOURCE)

vim -Nu <(cat << EOF
syntax on
let mapleader = ' '
for dep in ['vader.vim', 'vim-pseudocl', 'vim-repeat']
  execute 'set rtp+=' . finddir(dep, expand('~/.vim').'/**')
endfor
set rtp+=..
EOF) +'Vader*'

