#!/bin/bash

SOURCE=$(dirname $BASH_SOURCE)/..

vim -Nu <(cat << EOF
syntax on
let mapleader = ' '
for dep in ['vader.vim', 'vim-pseudocl', 'vim-repeat']
  execute 'set rtp+=' . finddir(dep, expand('~/.vim').'/**')
endfor
set rtp+=$SOURCE
EOF) +'Vader*'

